In [2]:
data = 123
data

123

In [3]:
my_list = [1, 2, 3]
len(my_list)

3

In [3]:
import numpy as np

In [5]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [6]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [8]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr1.shape

(5,)

In [11]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [13]:
arr2.dtype

dtype('int32')

In [15]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [17]:
arr3.dtype

dtype('float64')

In [18]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
arr4.shape

(4, 3)

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

In [25]:
print(arr1.shape, arr2.shape)

(2, 3) (2, 3)


In [26]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [27]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [28]:
arr3 = np.array([10, 11, 12])
arr3.shape

(3,)

In [29]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [7]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr2[1:,]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2 > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [10]:
arr2[arr2 > 7]

array([ 8,  9, 10, 11, 12])